.\"                                                              -*- nroff -*-
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)syslog.conf.5	8.1 (Berkeley) 6/9/93
.\" $FreeBSD$
.\"
.Dd Dec 31, 2024
.Dt SYSLOG.CONF 5
.Os sysklogd
.Sh NAME
.Nm syslog.conf
.Nd configuration file format for
.Xr syslogd 8
.Sh DESCRIPTION
The
.Nm
file is the configuration file for
.Xr syslogd 8 ,
it consists of rules for logging and controlling daemon behavior.
Logging rules are blocks of lines separated by optional
.Em program, hostname, or property-based
filter specifications.  Each rule in such a block contains at least two
fields: the
.Em selector
field which specifies the types of messages and priorities to which the
line applies, and an
.Em action
field which specifies the action to be taken if a message
.Xr syslogd 8
receives matches the selection criteria.  A rule may also have an
.Em option
field, e.g., to select log format.
.Pp
The fields are separated by one or more tab characters or spaces.  A
rule may be divided into several lines if the leading line ends with a
single backslash ('\\') character.
.Pp
.Bd -literal -offset indent
PROGRAM  := !IDENT[,IDENT]
         |= !!IDENT[,IDENT]
         |= !+IDENT[,IDENT]
	 |= !-IDENT[,IDENT]
HOSTNAME := +IDENT[,IDENT]
         |= ++IDENT[,IDENT]
	 |= -IDENT[,IDENT]
PROPERTY := :PROP, [PREFIX]OPERATOR, "VALUE"
         |= ::PROP, [PREFIX]OPERATOR, "VALUE"
PROP     := hostname
	 |= msg
         |= msgid
         |= propertyname
         |= sd
         |= data
	 |= source
OPERATOR := contains
         |= isequal
         |= startswith
         |= regex
         |= eregex
PREFIX   := [PREFIX]
         |= !
         |= icase_
RULE     := SELECTOR  ACTION  [;OPTION]
SELECTOR := [SELECTOR;]facility[,facility].[!=]severity
ACTION   := [+][-]/path/to/file
         |= [+]|/path/to/named/pipe
	 |= @remote[.host.tld][:PORT]
	 |= @@remote[.host.tld][:PORT]
	 |= @@@remote[.host.tld][:PORT]
	 |= tcp[4|6]://remote[.host.tld][:PORT]
	 |= tls[4|6]://remote[.host.tld][:PORT]
OPTION   := [OPTION,]
	 |= RFC3164
	 |= RFC5424
	 |= pri
	 |= iface=IFNAME
         |= rotate=ROT
	 |= ttl=1..255
	 |= verify=off|optional|required|hostname
	 |= fingerprint=SHA256:...
	 |= tls_keyfile=PATH
	 |= tls_certfile=PATH
ROT      := SIZE:COUNT
         |= SIZE
	 |= :COUNT

udp_size 480..2048

secure_mode [0,1,2]

tcp_suspend_time SECONDS

rotate_size  SIZE
rotate_count NUMBER

tls_keyfile   /path/to/server.key
tls_certfile  /path/to/server.cert
tls_cafile    /path/to/ca.pem
tls_capath    /path/to/ca.d
tls_verify    off|optional|required

listen [address:port[%iface] | :port | address[%iface] | tcp://... | tls://...]

include /etc/syslog.d/*.conf
notify  /path/to/script-on-rotate

membuf  /path/to/socket SIZE [USER:GROUP]
.Ed
.Pp
Each block of rules is separated from the previous block by a
.Em program , hostname ,
or
.Em property-based
filter specification.  A block only logs messages corresponding to the
most recent
.Em program , hostname
and
.Em property-based
filter specification given.  Thus, a block with a
.Ql ppp
.Em program
filter directly followed by another block
.Ql dialhost
.Em hostname
filter will only log
.Xr ppp 8
messages from dialhost.  For an example, see
.Sx Program and Hostname Filtering .
.Pp
A
.Em program filter
specification is a line starting with
.Ql #!prog
or
.Ql !prog
(the former is for compatibility with other syslogd implementations) and
the following rules are then associated with this specification only.  The
.Ql #!+prog
or
.Ql !+prog
specification works just like the previous one,
and the
.Ql #!-prog
or
.Ql !-prog
specification will match any message
.Em excluding
prog.  Multiple programs may be listed, separated by commas:
.Ql !prog1,prog2
matches messages from either program, while
.Ql !-prog1,prog2
matches all messages except those from
.Ql prog1
or
.Ql prog2 .
You can reset the program specification at any time using the
.Ql !*
syntax.  The program specification is also reset for each included .conf
file.
.Pp
The
.Ql !!prog
form works like
.Ql !prog
but causes evaluation to stop after a matching rule in this block fires,
ensuring no further rules are applied to that message.
Use
.Ql !*
to cancel the effect and resume normal evaluation for subsequent blocks.
.Pp
A
.Em hostname filter
specification of the form
.Ql #+hostname
or
.Ql +hostname
means the following blocks will be applied to messages received from the
specified hostname.  Alternatively, the
.Em hostname
specification
.Ql #-hostname
or
.Ql -hostname
causes the following blocks to be applied to messages from any host
.Em except
the one(s) specified.  If the hostname is given as
.Ql @ ,
the local hostname will be used.  Similar to program specifications,
multiple comma-separated values may be specified for hostname
specifications.
.Pp
The
.Ql ++hostname
form works like
.Ql +hostname
but causes evaluation to stop after a matching rule in this block fires,
ensuring no further rules are applied to that message.
Use
.Ql +*
to cancel the effect and resume normal evaluation for subsequent blocks.
.Pp
A
.Em property-based filter
specification is a line beginning with
.Ql #:
or
.Ql :
and the following blocks will be applied only when filter value matches
given filter properties value.
The
.Ql ::
form works like
.Ql :
but causes evaluation to stop after a matching rule in this block fires,
ensuring no further rules are applied to that message.
Use
.Ql :*
to cancel the effect and resume normal evaluation for subsequent blocks.
See
.Sx PROPERTY-BASED FILTERS
section for more details.  For examples, see
.Sx EXAMPLES
section, below.
.Pp
The
.Em selector
field specifies a pattern of facilities and priorities belonging to the
specified action.  The
.Em action
details where or what to do with the selected input.  The
.Em option
field, which must start with the semi-colon option delimiter (';'),
currently supports priority, log formatting, log rotation, outbound
interface and TTL when forwarding to a multicast group.
.Pp
The default log format is the traditional RFC3164 (included here for
completeness),
.Sy except
for remote syslog targets where the BSD format (without both timestamp
and hostname) is the default.  The user must explicitly set RFC3164 on
a remote logging target.  RFC5424 is the newest format with RFC3339 time
stamps, msgid, structured data, and more.  The BSD format cannot be set,
it is only the default for remote targets for compatibility reasons.
.Pp
.Bl -tag -compact -width "RFC3164:"
.It Sy BSD:
.Li myproc[8710]: Kilroy was here.
.It Sy RFC3164:
.Li Aug 24 05:14:15 192.0.2.1 myproc[8710]: Kilroy was here.
.It Sy RFC5424:
.Li 2003-08-24T05:14:15.000003-07:00 192.0.2.1 myproc 8710 - - Kilroy was here.
.El
.Pp
By default,
.Nm sysklogd
does not print the priority of a message. However, it will if
.Sy pri
is added to the options. Printing the priority adds the priority in
angled brackets to the message header in accordance with the RFC
standard in use. Below is an example using the user-level facility and a
warning severity.
.Pp
.Bl -tag -compact -width "RFC3164:"
.It Sy RFC3164:
.Li <12> Aug 24 05:14:15 192.0.2.1 myproc[8710]: Kilroy was here.
.It Sy RFC5424:
.Li <12>1 2003-08-24T05:14:15.000003-07:00 192.0.2.1 myproc 8710 - - Kilroy was here.
.El
.Pp
The log rotation, which is only relevant for files, details the max
.Ar SIZE:COUNT
a file can reach before it is rotated, and later compressed.  This
feature is mostly intended for embedded systems that do not want to have
cron or a separate log rotate daemon.  It is possible to specify only
size or count, in which case the global setting covers the other.  E.g.,
to set only the rotation count, use:
.Ar rotate=:COUNT .
.Pp
The
.Ql rotate_size SIZE
and
.Ql rotate_count COUNT
are the same as the
.Nm syslogd Fl r Ar SIZE:COUNT
command line option.  Remember, command line options take precedence
over .conf file settings.
.Pp
.Sy Note:
the permissions of the rotated files are kept.  Meaning the
administrator can create all log files, before starting
.Nm
the first time, with the permissions needed for the site.  However, if
the log files do not exist,
.Nm
will create them with the user and group it runs as and 0644
permissions.
.Pp
Forwarding of messages to another syslog server is accomplished with the
.Ql @
prefix to a hostname, an IP address, or a multicast group.  All IPv6
addresses must be enclosed in brackets.  For multicast groups both an
outbound interface and TTL can be se, per log target.  By default the
routing table is used (by the kernel) and the TTL defaults to 1, unlike
unicast which defaults to 64.
.Pp
Comments, lines starting with a hash mark ('#'), and empty lines are
ignored.  If an error occurs during parsing the whole line is ignored.
.Pp
The
.Ql udp_size 480..2048
option controls the maximum size of the UDP payload, which is the full
syslog message including the header.  This setting is the same as the
command line option
.Fl M ,
which like all command line options take precedence.  The default (1024
bytes) follow RFC3164.  Before tweaking this, please read section 3.2 of
RFC5426, it recommends 480 bytes for IPv4 and 1180 bytes for IPv6 to
avoid fragmentation.
.Pp
The
.Ql secure_mode <0-2>
option is the same as the
.Nm syslogd Fl s
command line option.
.Sy Note:
again, command line option always wins, so you need to drop
.Fl s
from the command line to use this .conf file option instead.
.Pp
.Bl -tag -compact -width "01" -offset indent
.It 0
act as a syslog sink, listening on UDP port 514 by default, as well as
support for sending to remote syslog servers
.It 1
only support for sending to remote syslog servers, no Internet ports
open
.It 2
no Internet ports open at all, and no remote logging possible
.El
.Bd -literal -offset indent
# Example: only allow logging to remote servers
secure_mode 1
.Ed
.Pp
The
.Ql listen Op Ar address:port[%iface] | address[%iface] | :port | tcp://address:port
option is the same as the
.Nm syslogd Fl b Ar addr[:port][%iface]
command line option.  Like its counterpart it has no effect unless the
.Ql secure_mode
option is disabled.  Multiple listen statements are allowed and any
command line directives are treated as "static" and cannot be removed or
modified using the configuration file.  Both unicast IP and multicast
group addresses are supported, enclose IPv6 addresses in brackets.
Multicast groups are "joined" using an OS-level
.Fn setsockopt
call, most operating systems translate this to IGMP/MLD membership
reports on the network.  The optional
.Ql %iface
syntax is for multicast groups, it allows joining a group on a given
interface (by name).  If the interface is omitted the routing table is
used, which often is not desirable for multicast.
.Pp
To listen for incoming TCP syslog connections, prefix the address with
.Ql tcp:// .
For example,
.Ql listen tcp://[::]:1514
listens on all interfaces, port 1514, for TCP connections.  Both
RFC 6587 octet counting and non-transparent (LF-delimited) framing
are supported on incoming TCP connections.
.Pp
The
.Ql tcp_suspend_time Ar seconds
option sets the number of seconds a TCP forwarding destination remains
suspended after a connection failure before a reconnection is attempted.
The default is 180 seconds.
.Pp
During the suspension window, messages destined for the failed remote host
are held in an in-memory per-destination queue rather than dropped.  When
.Xr syslogd 8
successfully reconnects, the queue is flushed in order before the current
message is sent.  The queue is bounded by compile-time limits (1000
messages or 1 MiB of payload per destination, whichever is reached first);
when a limit is exceeded, the oldest queued entry is evicted to make room
for the new one, and a warning is logged once per overflow event.
.Pp
.Sy Note:
the queue is discarded when
.Xr syslogd 8
receives
.Dv SIGHUP
or exits.  For persistent queueing across restarts, use an external log
shipper.
.Pp
The
.Ql notify <PATH>
option specifies the path to an executable program which will get called
whenever a log file has been rotated, with the name of the file, less
its rotation suffix
.Ql .0 ,
as an argument.
For example:
.Ql notify /sbin/on-log-rotate.sh .
Any number of notifiers may be installed.
.Pp
The
.Ql membuf Ar PATH SIZE Op Ar USER:GROUP
option enables an in-memory log buffer, in the style of BusyBox and
OpenWRT, read with
.Xr logread 1 .
It is disabled by default.  Every message is captured in a circular
buffer of at most
.Ar SIZE
bytes
.Pq e.g. Ql 128k ,
oldest lines evicted first, and served to
.Xr logread 1
over a UNIX domain control socket at
.Ar PATH .
The buffer lives in memory only and is lost on restart, which suits
embedded systems where writing to flash is undesirable.
.Pp
Access to the buffer is governed by the ownership and permission of the
control socket.  The optional
.Ar USER:GROUP
sets its owner and group; connecting requires write permission, so the
socket is created mode
.Ql 0660
.Pq owner and group .
Either part may be omitted, e.g.
.Ql :adm .
When
.Ar USER:GROUP
is not given, the socket is owned by root and the
.Ql adm
group if that group exists, otherwise it falls back to root only, mode
.Ql 0600 .
A configured user or group that cannot be resolved likewise falls back to
root-only access rather than widening it.
.Pp
.Sy Note:
place the socket in a directory writable only by root (the default
.Ar PATH
under
.Pa /run
is).  A directory writable by others lets them tamper with the socket
node before its ownership is applied.
.Pp
The
.Ql include <PATH/*.conf>
option can be used to include all files with names ending in '.conf' and
not beginning with a '.' contained in the directory following the
keyword.  This keyword can only be used in the first level configuration
file.  Included files are parsed in glob order and their rules are
inserted into the rule list at the position of the
.Ql include
line.
.Pp
This ordering matters for stop-processing blocks
.Pq Ql !! , ++ , ::
\&: such a block can only suppress rules that appear
.Em after
it in the parsed list.  Rules already processed before the
.Ql include
line are unaffected.  For snippets in
.Pa /etc/syslog.d/
to be able to prevent messages from reaching the general catch-all rules
in the main configuration file, the
.Ql include
line must appear
.Em before
those catch-all rules.  The shipped
.Pa /etc/syslog.conf
is structured accordingly.
.Pp
.Bd -literal -offset indent
#
# Drop your subsystem .conf file in /etc/syslog.d/
#
include /etc/syslog.d/*.conf
.Ed
.Sh SIGNED SYSLOG MESSAGES
When compiled with OpenSSL support
.Pq Fl -with-openssl ,
.Nm syslogd
can generate cryptographically signed syslog messages per RFC 5848.
This provides origin authentication, message integrity verification,
replay resistance, and detection of missing messages.
.Pp
.Bl -tag -width "sign_delim_sg2" -compact
.It Ql sign_sg Ar mode
Enable signing with the specified signature group mode:
.Pp
.Bl -tag -compact -width "0" -offset indent
.It 0
Single signature group for all messages (default)
.It 1
One signature group per priority level (192 groups maximum)
.It 2
Signature groups for priority ranges, using delimiters
.It 3
One signature group per destination (NetBSD extension)
.El
.Pp
.It Ql sign_delim_sg2 Ar delimiters
Space-separated priority values (0-191, facility*8+severity) defining the
upper bound of each signature group range for
.Ql sign_sg=2
mode.
With no delimiters configured all messages fall into a single group.
.Pp
.It Ql sign_keyfile Ar path
Path to PEM-encoded private key file for signing messages.
This option is required to enable signing.
.Pp
.It Ql sign_certfile Ar path
Path to PEM-encoded X.509 certificate file.
Optional; used for certificate block transmission to receivers.
.El
.Pp
Example configuration:
.Bd -literal -offset indent
# Sign every message (global signature group, SG=0) and log locally in
# RFC5424 format.  The signature and certificate blocks are themselves
# RFC5424 messages, emitted to this destination too.
sign_sg        0
sign_keyfile   /etc/syslog.d/syslog.key
sign_certfile  /etc/syslog.d/syslog.cert

*.*            /var/log/syslog          ;RFC5424
.Ed
.Pp
Signature blocks (SD-ID:
.Ql ssign )
are sent periodically (every 30 seconds by default) and contain
SHA-256 hashes of recent messages along with a digital signature.
Certificate blocks (SD-ID:
.Ql ssign-cert )
are sent at startup and periodically to distribute the public key
to receivers.
.Pp
The blocks are ordinary RFC5424 messages.  The certificate block carries
the base64 X.509 public key (long base64 fields truncated below):
.Bd -literal -offset indent
[ssign-cert VER="0121" RSID="208672719837483" SG="0" SPRI="0" \\
    TBPL="294" INDEX="1" FLEN="294" FRAG="MIIBIjANBgkq..." \\
    SIGN="MEUCIQDx9c2V...g=="]
.Ed
.Pp
Each signature block binds the SHA-256 hashes of the messages seen since
the previous block:
.Ql CNT
is the hash count,
.Ql HB
the space-separated base64 hashes, and
.Ql SIGN
the signature over the preceding fields.
.Bd -literal -offset indent
[ssign VER="0121" RSID="208672719837483" SG="0" SPRI="0" GBC="1" \\
    FMN="1" CNT="5" HB="d2hLpQ8r... 9fK1mZ0w... Qm7Xy4Tn..." \\
    SIGN="MEQCIBxK7m2P...Jr9w=="]
.Ed
.Pp
.Sy Note:
generating keys requires OpenSSL:
.Bd -literal -offset indent
openssl genrsa -out /etc/syslog.d/syslog.key 2048
openssl req -new -x509 -key /etc/syslog.d/syslog.key \\
    -out /etc/syslog.d/syslog.cert -days 365 -subj "/CN=syslog"
chmod 600 /etc/syslog.d/syslog.key
.Ed
.Pp
.Sy Verifying signatures.
The blocks let a downstream consumer detect tampering: recompute the
SHA-256 hash of each received message, check it against the
.Ql HB
list, and verify
.Ql SIGN
against the public key from the certificate block.  An altered message
fails the hash check; a dropped, inserted, or reordered message leaves a
gap in the
.Ql CNT ,
.Ql FMN ,
and
.Ql GBC
counters.
.Pp
.Sy Note:
.Nm syslogd
only produces signatures.  It ships no verifier, and acting as a
verifying sink for signed messages is not yet implemented.  This matches
the *BSD lineage the feature comes from (NetBSD), where signing is
producer-side and verification is left to separate RFC 5848-aware
tooling.
.Pp
Signing is independent of transport.  It works with remote forwarding
(the signature and certificate blocks are sent to every destination,
local and remote), and is orthogonal to TLS: signing gives end-to-end,
at-rest tamper evidence that survives relaying and storage, while TLS
only encrypts and authenticates a single hop in transit.  Use both for
confidentiality together with tamper evidence.
.Pp
Note that if you use spaces as separators, your
.Nm
might be incompatible with other Unices or Unix-like systems.
This functionality was added for ease of configuration
(e.g.\& it is possible to cut-and-paste into
.Nm ) ,
and to avoid possible mistakes.
This change however preserves
backwards compatibility with the old style of
.Nm
(i.e., tab characters only).
.Sh SELECTORS
The selector field consists of two parts, a
.Em facility
and a 
.Em priority ,
separated by a period ('.').  Both parts are case insensitive and can
also be specified as decimal numbers corresponding to the definitions in
.Pa /usr/include/syslog.h .
It is safer to use symbolic names rather than decimal numbers.  Both
facilities and priorities are described in
.Xr syslogp 3 .
The names mentioned below correspond to the similar 
.Ql LOG_FOO
values in
.Pa /usr/include/syslog.h .
.Pp
The
.Em facility
is one of the following keywords:
.Bl -column "Code" "Facility" "Description" -offset indent
.It Sy "Code" Ta Sy "Facility" Ta Sy "Description"
.It        0  Ta         kern  Ta Kernel log messages
.It        1  Ta         user  Ta User-level messages
.It        2  Ta         mail  Ta Mail system
.It        3  Ta       daemon  Ta General system daemons
.It        4  Ta         auth  Ta Security/authorization messages
.It        5  Ta       syslog  Ta Messages generated by syslogd
.It        6  Ta          lpr  Ta Line printer subsystem
.It        7  Ta         news  Ta Network news subsystem
.It        8  Ta         uucp  Ta UNIX-to-UNIX copy
.It        9  Ta         cron  Ta Clock/cron daemon (BSD, Linux)
.It       10  Ta     authpriv  Ta Security/authorization messages (private)
.It       11  Ta          ftp  Ta FTP daemon
.It       12  Ta          ntp  Ta NTP subsystem
.It       13  Ta     security  Ta Log audit
.It       14  Ta      console  Ta Log alert
.It       15  Ta       unused  Ta Clock/cron daemon (Solaris)
.It       16  Ta       local0  Ta Reserved for local/system use
.It       17  Ta       local1  Ta Reserved for local/system use
.It       18  Ta       local2  Ta Reserved for local/system use
.It       19  Ta       local3  Ta Reserved for local/system use
.It       20  Ta       local4  Ta Reserved for local/system use
.It       21  Ta       local5  Ta Reserved for local/system use
.It       22  Ta       local6  Ta Reserved for local/system use
.It       23  Ta       local7  Ta Reserved for local/system use
.El
.Pp
Notice, several of the above listed facilities are not supported by the
standard C library (GLIBC, musl libc, or uClibc) on Linux.  libsyslog,
shipped with
.Nm sysklogd ,
however, supports all the above facilities in full.  Also, the keyword
.Ql mark
is only for internal use and should therefore not be used in
applications.  The
.Em facility
specifies the subsystem that produced the message, e.g. all mail
programs log with the mail facility,
.Ql LOG_MAIL ,
if they log using syslog.
.Pp
In most cases anyone can log to any facility, so we rely on convention
for the correct facility to be chosen.  However, generally only the
kernel can log to the
.Ql kern
facility.  This because the implementation of
.Xr openlog 3
and
.Xr syslog 3
in GLIBC does not allow logging to the
.Ql kern
facility.
.Pp
The
.Em priority
is one of the following keywords, in ascending order:
.Bl -column "Code" "Facility" "Description" -offset indent
.It Sy "Value" Ta Sy "Severity" Ta Sy "Description"
.It         0  Ta    emergency  Ta System is unusable
.It         1  Ta        alert  Ta Action must be taken immediately
.It         2  Ta     critical  Ta Critical conditions
.It         3  Ta        error  Ta Error conditions
.It         4  Ta      warning  Ta Warning conditions
.It         5  Ta       notice  Ta Normal but significant conditions
.It         6  Ta         info  Ta Informational messages
.It         7  Ta        debug  Ta Debug-level messages
.El
.Pp
The default log level of most applications is
.Ql notice ,
meaning only
.Ql notice
and above are forwarded to
.Nm syslogd .
See
.Xr setlogmask 3
for more information on how to change the default log level of your
application.
.Pp
In addition to the above mentioned facility and priority names,
.Xr syslogd 8
understands the following extensions:
.Pp
.Bl -tag -compact -width "'none'"
.It *
An asterisk ('*') matches all facilities or all priorities, depending on
where it is used (before or after the period).
.It none
The keyword
.Ql none
stands for no priority of the given facility.
.It ,
Multiple facilities may be specified for a single priority pattern in
one statement using the comma (',') operator to separate the facilities.
You may specify as many facilities as you want.  Please note that only
the facility part from such a statement is taken, a priority part would
be ignored.
.It ;
Multiple selectors may be specified for a single
.Em action
using the semicolon (';') separator.  Selectors are processed from left
to right, with each selector being able to overwrite preceding ones.
Using this behavior you are able to exclude some priorities from the
pattern.
.It =
This version of
.Xr syslogd 8
has a syntax extension to the original BSD source, which makes its use
more intuitive.  You may precede every priority with an equation sign
('=') to specify that only this single priority should be matched,
instead of the default: this priority and all higher priorities.
.It !
You may also precede the priority with an exclamation mark ('!') if you
want to ignore this priority and all higher priorities.  You may even
use both the exclamation mark and the equation sign if you want to
ignore a single priority.  If both extensions are used, the exclamation
mark must occur before the equation sign.
.El
.Sh ACTIONS
The action field of a rule is the destination or target for a match.  It
can be a file, a UNIX named pipe, the console, or a remote machine.
.Ss Regular File
Typically messages are logged to real files.  The filename is specified
with an absolute path name.
.Pp
You may prefix each entry with a minus sign ('-') to avoid syncing the
file after each log message.  Note that you might lose information if
the system crashes right after a write attempt.  Nevertheless this might
give you back some performance, especially if you run programs that use
logging in a very verbose manner.
.Pp
To keep RFC 5848 signature verification possible for a file destination,
log it in a format that preserves the priority, by prefixing the path
with
.Ql + ,
matching NetBSD.  This is equivalent to the
.Ql ;pri
option, and may be combined with the no-sync prefix as
.Ql +-
(in that order).  To also keep the RFC5424 version field, use the
.Ql ;RFC5424
format.
.Ss Named Pipes
This version of
.Xr syslogd 8
supports logging to named pipes (FIFOs).  A FIFO, or named pipe, can be
used as a destination for log messages by prepending a pipe symbol ('|')
to the name of the file.  This can be very handy for debugging.  Note
that the FIFO must be created with the
.Xr mkfifo 1
command before
.Nm syslogd
is started.
.Ss Terminal and Console
If the file you specified is a tty, special tty-handling is done, same
with
.Pa /dev/console .
.Ss Remote Machine
Full remote logging support is available in
.Nm syslogd ,
i.e. to send messages to a remote syslog server, and to receive
messages from remote hosts.  To forward messages to another host
over UDP, prepend the hostname with the at sign ('@').  For TCP
forwarding, use a double at sign ('@@') or the
.Ql tcp://
URL syntax.  If a port number is added
after a colon (':') then that port will be used as the destination port
rather than the usual syslog port.
.Pp
The address family is otherwise selected automatically.  Append a
.Ql 4
or
.Ql 6
to the URL scheme to force IPv4 or IPv6, e.g.
.Ql tcp4://remote
or
.Ql tls6://remote ,
which is useful for dual-stack hosts.
.Pp
TCP forwarding uses RFC 6587 octet counting for framing.  On the
receiving side, both octet counting and non-transparent (LF-delimited)
framing are supported.  To listen for TCP connections, use
.Ql listen tcp://address:port
in the configuration file.
.Pp
When a TCP connection to a remote host fails,
.Xr syslogd 8
enters a suspension state for
.Ql tcp_suspend_time
seconds (default 180).  During this window, messages are accumulated in
an in-memory per-destination send queue instead of being dropped.  Once
the suspension window expires and a new message arrives,
.Xr syslogd 8
attempts to reconnect.  On success, any queued messages are flushed to
the remote host in order before the triggering message is sent.
.Pp
TLS forwarding per RFC 5425 is also available when compiled with
OpenSSL support.  Use a triple at sign ('@@@') or the
.Ql tls://
URL syntax.  The default port for TLS is 6514.  TLS provides
encryption and optional certificate-based authentication.  To listen
for TLS connections, use
.Ql listen tls://address:port
in the configuration file.  Server certificates are configured with
.Ql tls_keyfile
and
.Ql tls_certfile
global options.  Per-action TLS options include
.Ql verify=off|optional|required|hostname ,
.Ql fingerprint=SHA256:...
for certificate pinning, and
.Ql tls_keyfile=
with
.Ql tls_certfile=
to present a client certificate for mutual TLS, distinct from the global
server identity above.
.Pp
The
.Ql verify=
modes differ in strictness:
.Ql off
does not check the server certificate;
.Ql optional
validates the chain when a certificate is presented but proceeds (with a
warning) if validation fails;
.Ql required
demands a certificate that chains to a trusted CA configured with
.Ql tls_cafile
or
.Ql tls_capath ;
and
.Ql hostname
additionally requires the certificate name to match the forwarding target.
.Pp
This feature makes it possible to collect all syslog messages in a
network on a central host.  This reduces administration needs and
can be really helpful when debugging distributed systems.
.Pp
Using a named pipe log method, messages from remote hosts can be sent to
a log program.  By reading log messages line by line such a program is
able to sort log messages by host name or program name on the central
log host.  This way it is possible to split the log into separate files.
.Pp
By default messages to remote remote hosts were formatted in the original
BSD style, without timestamp or hostname.  As of
.Nm syslogd
v2.0 the default includes timestamp and hostname.  It is also possible to
enable the new RFC5424 style formatting, append ';RFC5424' after the
hostname.
.Ss TLS Certificates and Trust
TLS authenticates the server (receiver) to the forwarding client, and
optionally the client to the server (mutual TLS).  Keys are private,
certificates are public: a
.Ql .key
file is secret, never distributed (chmod 600), while a
.Ql .crt
or
.Ql .cert
file is public and may be distributed freely.
.Pp
The receiver presents its identity with the global
.Ql tls_keyfile
(private) and
.Ql tls_certfile
(public), and listens with
.Ql listen tls://addr:port .
A forwarding client trusts that certificate by trusting the CA that
signed it: set the global
.Ql tls_cafile
to the CA's public certificate and
.Ql verify=required
(or
.Ql verify=hostname )
on the action.  With no CA, pin the exact certificate instead with
.Ql fingerprint=SHA256:... .
For mutual TLS the client adds the per-action
.Ql tls_keyfile=
and
.Ql tls_certfile= ,
and the receiver demands them with
.Ql tls_cafile
and
.Ql tls_verify required .
.Pp
To create your own certificates, for example a private CA that signs a
receiver certificate:
.Bd -literal -offset indent
# A CA: distribute ca.crt to every forwarder, keep ca.key secret.
openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \\
    -keyout ca.key -out ca.crt -subj "/CN=My Syslog CA"

# A receiver certificate with CN set to the receiver's hostname,
# signed by the CA.
openssl req -newkey rsa:2048 -nodes \\
    -keyout server.key -out server.csr -subj "/CN=loghost.example"
openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key \\
    -CAcreateserial -out server.crt -days 825
.Ed
.Pp
Install
.Pa server.key
and
.Pa server.crt
on the receiver, and copy the public
.Pa ca.crt
to each forwarder for its
.Ql tls_cafile .
.Ss List of Users
Usually critical messages are also directed to
.Ql root
on that machine.  You can specify a list of users that ought to receive
the log message on their terminal by writing their usernames.  You may
specify more than one user by separating the usernames with commas
(',').  Only logged in users will receive the log messages.
.Ss Everyone logged on
Emergency messages often go to all users currently online to notify them
that something strange is happening with the system.  To specify this
.Xr wall 1
feature use an asterisk ('*').
.Sh PROPERTY-BASED FILTERS
The
.Em program
and
.Em hostname
specifications perform exact match filtering against explicit fields
only.  Property-based filters feature substring and regular expression
matching, (see
.Xr re_format 7 )
on various message properties.  Property filter specifications starts
with
.Ql #:
or
.Ql \&:
followed by three comma-separated fields
.Em property , operator , \&"value\&" .
The value field
.Sy must
be double-quoted.  A double quote and backslash must be escaped by a
backslash.
.Pp
The following properties are supported as test value:
.Pp
.Bl -tag -compact -width "programname" -offset indent
.It msg
Body of the message received
.It msgid
Message ID.  Only available for messages received in RFC5424 format
.It sd
Structured data.  Only available for messages received in RFC5424 format
.It data
Alias for
.Ql sd
.It programname
Name of program that sent the message
.It hostname
Hostname of message's originator
.It source
Alias for
.Ql hostname
.El
.Pp
The operator field specifies a comparison function between a message
property value against the filter's value.  Possible operators are:
.Pp
.Bl -tag -compact -width "startswith" -offset indent
.It contains
true if the filter value is found as a substring of property
.It isequal
true if the filter value is equal to property
.It startswith
true if the message property start with the filter value
.It regex
true if the message property matches basic regular expression defined in
the filter value
.It ereregex
true if the message property matches the extended regular expression
defined in the filter value
.It eregex
alias for
.Ql ereregex
.El
.Pp
An operator may be prefixed by
.Pp
.Bl -tag -compact -width "icase_" -offset indent
.It !
to invert compare logic
.It icase_
to make comparison function case-insensitive
.El
.Pp
For examples, please see the
.Sx EXAMPLES
section, below.
.Sh IMPLEMENTATION NOTES
The
.Dq kern
facility is usually reserved for messages
generated by the local kernel.
Other messages logged with facility
.Dq kern
are usually translated to facility
.Dq user .
This translation can be disabled;
see
.Xr syslogd 8
for details.
.Sh FILES
.Bl -tag -width /etc/syslog.d/*.conf -compact
.It Pa /etc/syslog.conf
.Xr syslogd 8
configuration file
.It /etc/syslog.d/*.conf
Recommended directory for .conf snippets
.El
.Sh EXAMPLES
This section lists some examples, partially from actual site setups.
.Ss Applying Changes
After editing this file, tell the running
.Xr syslogd 8
to reload it; changes do not take effect until then.  Send it
.Dv SIGHUP ,
using the PID file so you need not look up the process ID first:
.Bd -literal -offset indent
kill -HUP `cat /var/run/syslogd.pid`
.Ed
.Pp
On a
.Xr systemd 1
host use
.Ql systemctl reload syslogd
instead.  A reload rereads
.Pa /etc/syslog.conf
and all
.Ql include
snippets, reopens log files, and re-resolves forwarding targets; there
is no need to restart.
.Ss Catch Everything
This example matches all facilities and priorities and stores everything
in the file
.Pa /var/log/syslog
in RFC5424 format.  Every time the file reaches 10 MiB it is rotated and
five files in total are kept, including the non-rotated file.
.Bd -literal -offset indent
# Match all log messages, store in RC5424 format and rotate every 10 MiB
#
*.*                          /var/log/critical    ;rotate=10M:5,RFC5424
.Ed
.Ss Program Based Filtering
In this example we funnel logs from a couple of multicast routing
daemons to their own log files.  The first exclusion filter ensure
the syslog file does not get either daemon's logs.
.Bd -literal -offset indent
# Match all log messages, except from certain programs
#
!-pimd,mrouted
*.*                          /var/log/syslog
!+pimd
*.*                          /var/log/pimd
!+mrouted
*.*                          /var/log/mrouted
.Ed
.Ss Hostname Based Filtering
Redirect logs from two remote hosts:
.Ql finlandia
and
.Ql sibelius ,
to their own dedicated log files.
.Bd -literal -offset indent
# Match all log messages, except from certain programs
#
-finlandia,sibelius
*.*                          /var/log/syslog
+finlandia
*.*                          /var/log/finlandia
+sibelius
*.*                          /var/log/sibelius
.Ed
.Ss Program and Hostname Filtering
This example shows one combination of program and hostname filters.
.Bd -literal -offset indent
# Log all local messages, except pppd
-finlandia,sibelius
!-ppp
*.*                          /var/log/syslog

# Local pppd messages of severity info, or higher, go to its own log file
!+ppp
*.info                       /var/log/ppp.log

# All pppd messages from host finlandia
+finlandia
*.*                          /var/log/finlandia.ppp.log

# All mrouted messages from host sibelius
# Note, any pppd messages from siblius are dropped
+sibelius
!+mrouted
*.*                          /var/log/sibelius.mrouted.log
.Ed
.Ss Property Based Filtering
These examples show off the substring and regexp matching capabilities.
.Bd -literal -offset indent
# Catch any message that has the substring 'error'
:msg, icase_contains, "ERROR"
*.*			     /var/log/error.log

# Log messages from bird or bird6 into one file
:programname, regex, "^bird6?$"
*.*			     /var/log/bird-all.log

# Log messages from servers in racks 10-19 in multiple locations, case insensitive
:hostname, icase_ereregex, "^server-(dcA|podB|cdn)-rack1[0-9]{2}\..*"
*.*			     /var/log/racks10-19.log
.Ed
.Ss Stop Processing
In this example, firewall messages tagged with
.Ql [nftables
are captured in a dedicated log file and then processing stops,
preventing the same messages from also appearing in
.Pa /var/log/syslog .
Without the
.Ql ::
prefix on the property filter, both files would receive the message.
.Bd -literal -offset indent
# Capture firewall messages exclusively in their own log file.
# The :: prefix stops further rule evaluation once a match fires.
::msg, contains, "[nftables"
kern.*                       /var/log/nftables.log

# Reset the property filter, then log general kernel/warn messages.
# Firewall messages never reach this rule.
:*
*.warn;\e
    authpriv.none;cron.none;mail.none;news.none    /var/log/syslog
.Ed
.Pp
The same behaviour is available for program and hostname blocks.
Here, all messages from
.Nm spamd
are routed to their own log and nowhere else:
.Bd -literal -offset indent
!!spamd
daemon.info                  /var/log/spamd
!*
.Ed
.Pp
.Sy Note:
stop-processing only suppresses rules that follow the matching rule in
the parsed order.
A stop-block placed in a snippet under
.Pa /etc/syslog.d/
cannot suppress rules already parsed from the main configuration file
above the
.Ql include
line.
Place the
.Ql include
directive before any general catch-all rules so that snippets are
evaluated first.
.Ss Critical
This stores all messages of priority
.Ql crit
in the file
.Pa /var/log/critical ,
with the exception of any kernel messages.
.Bd -literal -offset indent
# Store critical stuff in critical
#
*.=crit;kern.none            /var/log/critical
.Ed
.Ss Kernel
This is an example of the 2nd selector overwriting part of the first
one.  The first selector selects kernel messages of priority
.Ql info
and higher.  The second selector filters out kernel messages of priority
.Ql error
and higher.  This leaves just priorities
.Ql info ,
.Ql notice ,
and
.Ql warning
to get logged.
.Bd -literal -offset indent
# Kernel messages are stored in the kernel file, critical messages and
# higher ones also go to another host and to the console
#
kern.*                       /var/log/kernel
kern.crit                    @arpa.berkeley.edu   ;RFC5424
kern.crit                    /dev/console
kern.info;kern.!err          /var/log/kernel.info
.Ed
.Pp
The first rule directs any message that has the kernel facility to the
file
.Pa /var/log/kernel .
Recall that only the kernel itself can log to this facility.
.Pp
The second statement directs all kernel messages of priority
.Ql crit
and higher to the remote host
.Ql arpa.berkeley.edu
in RFC5424 style formatting.  This is useful, because if the host
crashes and the disks get irreparable errors you might not be able to
read the stored messages.  If they're on a remote host, too, you still
can try to find out the reason for the crash.
.Pp
The third rule directs kernel messages of priority
.Ql crit
and higher to the actual console, so the person who works on the machine
will get them, too.
.Pp
The fourth line tells
.Nm syslogd
to save all kernel messages that come with priorities from
.Ql info
up to
.Ql warning
in the file
.Pa /var/log/kernel.info .
.Ss Redirecting to a TTY
This directs all messages that use 
.Ql mail.info
(in source
.Ql LOG_MAIL | LOG_INFO )
to
.Pa /dev/tty12 , 
the 12th console.  For example the tcpwrapper
.Xr tcpd 8 
uses this as its default.
.Bd -literal -offset indent
# The tcp wrapper logs with mail.info, we display
# all the connections on tty12
#
mail.=info                   /dev/tty12
.Ed
.Ss Redirecting to a file
This pattern matches all messages that come with the
.Ql mail
facility, except for the
.Ql info
priority.  These will be stored in the file
.Pa /var/log/mail .
.Bd -literal -offset indent
# Write all mail related logs to a file
#
mail.*;mail.!=info           /var/log/mail
.Ed
.Ss Single Priority from Two Facilities
This will extract all messages that come either with
.Ql mail.info
or with
.Ql news.info
and store them in the file
.Pa /var/log/info .
.Bd -literal -offset indent
# Log all mail.info and news.info messages to info
#
mail,news.=info              /var/log/info
.Ed
.Ss Advanced Filtering, part 1
This logs all messages that come with either the
.Ql info
or the
.Ql notice
priority into the file
.Pa /var/log/messages ,
except for all messages that use the
.Ql mail
facility.
.Bd -literal -offset indent
# Log info and notice messages to messages file
#
*.=info;*.=notice;\\
	mail.none            /var/log/messages
.Ed
.Ss Advanced Filtering, part 2
This statement logs all messages that come with the
.Ql info
priority to the file
.Pa /var/log/messages .
But any message with either
.Ql mail
or the
.Ql news
facility  are not logged.
.Bd -literal -offset indent
# Log info messages to messages file
#
*.=info;\\
	mail,news.none       /var/log/messages
.Ed
.Ss Wall Messages
This rule tells
.Nm syslogd
to write all emergency messages to all currently logged in users.  This
is the wall action.
.Bd -literal -offset indent
# Emergency messages will be displayed using wall
#
*.=emerg                     *
.Ed
.Ss Alerting Users
This rule directs all messages of priority
.Ql alert
or higher to the terminals of the operator, i.e. of the users 'root'
and 'eric', if they're logged in.
.Bd -literal -offset indent
# Any logged in root user and Eric get alert and higher messages.
#
*.alert                      root,eric
.Ed
.Ss Log Rotation
This example logs all messages except kernel messages to the file
.Pa /var/log/messages
without syncing ('-') the file after each log message.  When the file
reaches 100 kiB it is rotated.  In total are only 10 rotated files,
including the main file itself and compressed files kept.  The size
argument takes the same modifiers as the
.Xr syslogd 8
command line option,
.Fl r .
.Bd -literal -offset indent
# Log all messages, including kernel, to the messages file rotate it
# every 100 kiB and keep up to 10 aged out, and compressed, files.
#
*.*;kern.none               -/var/log/messages    ;rotate=100k:10
.Ed
.Ss Priority
The first example logs user messages to the file
.Pa /var/log/messages
with syncing and prints the priority for each message. The second
example logs syslog messages to the file
.Pa /var/log/syslog
without syncing and with the rotation from the above example, on top of
printing the priority for each message.
.Bd -literal -offset indent
# Turn on priority printing for each user and syslog message.
#
user.*                      /var/log/messages     ;pri
syslog.*                    -/var/log/syslog      ;rotate=100k:10,pri
.Ed
.Ss Logging to Remote Syslog Server
These rules redirect all messages to remote hosts.  The first is to
.Ql finlandia ,
with RFC5424 style formatting, the second to
.Ql sibelius ,
on a non-standard port and with RFC3164 formatting (i.e., including
timestamp and hostname).
.Pp
Two multicast groups are used
.Ql 225.1.2.3
and
.Ql 225.1.2.4
with a TTL set to 10 and 3, respectively, to allow the messages to be
routed beyond the LAN.  Messages to the first group will egress the
interface connected to the default route, and the second group's
messages will egress
.Ql eth2 .
.Bd -literal -offset indent
*.*                @finlandia      ;RFC5424
*.*                @sibelius:5514  ;RFC3164
*.*                @225.1.2.3      ;RFC3164,ttl=10
*.*                @225.1.2.4      ;RFC5424,iface=eth2,ttl=3
.Ed
.Pp
.Sy Note:
some may prefer a 224.0.0.0/4 interface route to direct all outbound
multicast via a given interface, but the
.Ql iface=
option above does this per log target, which is less intrusive.
.Ss Logging to Remote Syslog Server via TCP
TCP forwarding can be configured using either the
.Ql @@
prefix or the
.Ql tcp://
URL syntax.  Messages are framed using RFC 6587 octet counting.
To receive TCP connections, use
.Ql listen tcp://
in the configuration.
.Bd -literal -offset indent
# Forward to remote host via TCP
*.*                @@loghost:1514   ;RFC5424

# Same using tcp:// URL syntax
*.*                tcp://loghost:1514  ;RFC5424

# Listen for incoming TCP syslog connections
listen tcp://[::]:1514
.Ed
.Ss Logging to Remote Syslog Server via TLS
TLS forwarding per RFC 5425 uses the
.Ql @@@
prefix or the
.Ql tls://
URL syntax; the default port is 6514 and OpenSSL support must be compiled
in.  A TLS setup has two sides, configured on different machines; see
.Sx TLS Certificates and Trust
for which file is private, which is public, and where each belongs.
.Pp
On the forwarding host (the client) the action selects the transport and
how to verify the server it connects to:
.Bd -literal -offset indent
# No verification (testing only)
*.*    @@@loghost              ;RFC5424,verify=off

# Verify the collector against a CA (tls_cafile, below) ...
*.*    tls://loghost:6514      ;RFC5424,verify=required
# ... or also require its name to match the certificate ...
*.*    tls://loghost:6514      ;RFC5424,verify=hostname
# ... or pin its certificate directly, no CA needed
*.*    tls://loghost:6514      ;RFC5424,fingerprint=SHA256:abc123...

# Mutual TLS: also present our own client certificate
*.*    tls://loghost:6514      ;RFC5424,verify=required,tls_keyfile=/etc/client.key,tls_certfile=/etc/client.cert

# The CA that signed the collector's certificate (and our client cert)
tls_cafile  /etc/syslog.d/ca.crt
.Ed
.Pp
On the collecting host (the server) configure the identity it presents
and listen for connections:
.Bd -literal -offset indent
# The collector's own key (private) and certificate (public)
tls_keyfile   /etc/syslog.d/server.key
tls_certfile  /etc/syslog.d/server.cert

# To also authenticate clients (mutual TLS): trust their CA and require
# a client certificate from every forwarder
tls_cafile    /etc/syslog.d/ca.crt
tls_verify    required

listen tls://[::]:6514
.Ed
.Sh SEE ALSO
.Xr logread 1 ,
.Xr syslog 3 ,
.Xr syslogd 8
.Sh BUGS
The effects of multiple
.Em selectors
are sometimes not intuitive.
For example
.Dq mail.crit,*.err
will select
.Dq mail
facility messages at the level of
.Dq err
or higher, not at the level of
.Dq crit
or higher.
.Pp
In networked environments, note that not all operating systems
implement the same set of facilities.
The facilities
authpriv, cron, ftp, and ntp that are known to this implementation
might be absent on the target system.
Even worse, DEC UNIX uses
facility number 10 (which is authpriv in this implementation) to
log events for their AdvFS file system.
